# Use node.js + test on all supported versions
language: node_js
node_js:
  - 'stable'
  - '8'
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

# Use yarn 1.9.4
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn test
  - yarn test:coverage

# Upload coverage reports
after_script:
  - npm run report-coverage
